---
- hosts: webserver
  tasks:
  - name: installing java 
    apt: package=openjdk-8-jdk state=latest

  - name: Download Tomcat
    get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz dest=/root/ansible

  - name: Extract archive
    unarchive: src=/root/ansible/apache-tomcat-8.0.27.tar.gz dest=/root/ansible remote_src=yes

  - name: start apache-tomcat-8.0.27
    shell: /root/ansible/apache-tomcat-8.0.27/bin/startup.sh
